DELETE http://localhost:3001/api/blogs/666aa0ea858da9e0cc9293ba
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pa29sYXMiLCJpZCI6IjY2NTU3Nzk3M2NkMTZmZjA0YWYwMjE3YyIsImlhdCI6MTcxODI2NTQ3NSwiZXhwIjoxNzE4MjY5MDc1fQ.C_njSF8frXrL6QBlVrXHyt45GM0lVOZWFUEveqQFyOg
